<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8">
	<meta http-equiv="content-language" content="en">
	<meta http-equiv="imagetoolbar" content="no">
	<meta name="author" content="David Grudl">
	<meta name="copyright" content="David Grudl">
	<link rel="stylesheet" type="text/css" media="screen" href="{$basePath}/css/style.css">

	<title>Fifteen - Nette Framework example</title>

	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js" type="text/javascript"></script>
	<script src="{$basePath}/js/jquery.nette.js" type="text/javascript"></script>
	<script src="{$basePath}/js/fifteen.js" type="text/javascript"></script>
</head>

<body>
	<h1>Fifteen example &ndash; {snippet round <span>}round #{$presenter['fifteen']->round + 1}{/snippet}</h1>

	{snippet flash}<h2 n:ifset="$flash">{$flash}</h2>{/snippet}

	<p><a href="{link fifteen:shuffle!}" class="ajax">Shuffle!</a></p>

	@{control fifteen}
</body>
</html>
