<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/2000/REC-xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8">
	<meta http-equiv="content-language" content="en">
	<meta http-equiv="imagetoolbar" content="no">
	<meta name="author" content="David Grudl">
	<meta name="copyright" content="David Grudl">
	<link rel="stylesheet" type="text/css" media="screen" href="{$baseUri}css/style.css">

	<title>Fifteen - Nette Framework example</title>

	<script src="{$baseUri}js/nette.js" type="text/javascript"></script>
</head>

<body>
	<h1>Fifteen example</h1>

	{partial round}<p>Round #{$fifteen->round + 1}</p>{/partial round}

	{partial flash}{if isset($flash)}<h2>{$flash}</h2>{/if}{/partial flash}

	<p><a href="{$fifteen->link('shuffle')}" onclick="{$fifteen->ajaxLink(NULL)}">Shuffle!</a></p>

	<div>
	{? $fifteen->render() }
	</div>

	<img id="spinner" src="images/spinner.gif" alt="Wait please..." width="14" height="14">
</body>
</html>