<?php
// source: %a%

%A%
// prolog Nette\Bridges\CacheLatte\CacheMacro
Nette\Bridges\CacheLatte\CacheMacro::initRuntime($template, $_g);

//
// main template
//
?>
<p>Included file (<?php echo Latte\Runtime\Filters::escapeHtml($localvar, ENT_NOQUOTES) ?>)</p>

<?php if (Nette\Bridges\CacheLatte\CacheMacro::createCache($netteCacheStorage, '%[a-z0-9]+%', $_g->caches)) { ?>
	<?php echo Latte\Runtime\Filters::escapeHtml($template->lower($title), ENT_NOQUOTES) ?>

<?php $_l->tmp = array_pop($_g->caches); if (!$_l->tmp instanceof stdClass) $_l->tmp->end(); }
