<?php

/**
 * Routing debugger template.
 *
 * @param string   $presenter
 * @param array    $params
 * @param string   $router
 * @param array    $routers
 */

/*use Nette\Debug;*/
/*use Nette\Application\Presenter;*/

?>

<style type="text/css">
/* <![CDATA[ */
	#routingDebugger {
		position: fixed;
		_position: absolute;
		right: 5px;
		top: 5px;
		z-index: 23177;
		padding: 5px;
		font: 9pt/1.5 Consolas, monospace !important;
		color: black;
		background: #F5F5F5;
		border: 1px dotted gray;
	}

	#routingDebugger div {
		display: none;
	}

	#routingDebugger * {
		color: inherit;
		background: inherit;
		text-align: inherit;
	}

	#routingDebuggerIcon {
		padding: 4px;
		top: 0;
		right: 0;
		line-height: 1;
		color: black;
		text-decoration: none;
	}

	#routingDebugger h2 {
		font-size: 120%;
		color: black;
	}

	#routingDebugger table {
		padding: 0;
		margin: 0;
		border-collapse: collapse;
	}

	#routingDebugger table td, #routingDebugger table th {
		color: #444;
		background: #FFF;
		border: 1px solid #CCC;
		padding: 3px 6px;
		text-align: left;
	}

	#routingDebugger table th {
		color: #165ca3;
		background: #DDD;
		font-size: 90%;
	}

	#routingDebugger .may, #routingDebugger .yes {
		color: green;
	}

	#routingDebugger .yes {
		font-weight: bold;
	}

	#routingDebugger pre, #routingDebugger code {
		font: 9pt/1.5 Consolas, monospace !important;
		display: inline;
	}

/* ]]> */
</style>


<div id="routingDebugger">
	<a id="routingDebuggerIcon" href="#"><?php echo htmlSpecialChars($presenter . ':' . (isset($params[Presenter::ACTION_KEY]) ? $params[Presenter::ACTION_KEY] : Presenter::$defaultAction)) ?> <abbr>&#x25ba;</abbr></a
	><div>
	<?php if (!empty($presenter)): ?>
		<h2><?php echo htmlSpecialChars($presenter . ':' . (isset($params[Presenter::ACTION_KEY]) ? $params[Presenter::ACTION_KEY] : Presenter::$defaultAction)) ?></h2>
		<?php if (empty($params)): ?>
			<p>No parameters.</p>

		<?php else: ?>
			<table>
			<thead>
			<tr>
				<th>Parameter</th>
				<th>Value</th>
			</tr>
			</thead>
			<tbody>
			<?php foreach ($params as $key => $value): ?>
			<tr>
				<td><code><?php echo htmlSpecialChars($key) ?></code></td>
				<td><?php if (is_string($value)):?><code><?php echo htmlSpecialChars($value) ?></code><?php else: Debug::dump($value); endif ?></td>
			</tr>
			<?php endforeach ?>
			</tbody>
			</table>
		<?php endif ?>
	<?php endif ?>

	<!-- ~~~~~~~~~~~ -->

	<?php if (empty($router)): ?>
		<h2>Not matched</h2>

	<?php else: ?>
		<h2>Matched by <?php echo htmlSpecialChars($router) ?></h2>
	<?php endif ?>

	<!-- ~~~~~~~~~~~ -->

	<?php if (empty($routers)): ?>
		<p>No routes defined.</p>

	<?php else: ?>
		<table>
		<thead>
		<tr>
			<th>Matched?</th>
			<th>Class</th>
			<th>Mask</th>
			<th>Defaults</th>
		</tr>
		</thead>

		<tbody>
		<?php foreach ($routers as $router): ?>
		<tr>
			<td class="<?php echo $router['matched'] ?>"><?php echo $router['matched'] ?></td>
			<td><code><?php echo htmlSpecialChars($router['class']) ?></code></td>
			<td><code><strong><?php echo htmlSpecialChars($router['mask']) ?></strong></code></td>
			<td><code>
			<?php foreach ($router['defaults'] as $key => $value): ?>
				<?php echo htmlSpecialChars($key), "&nbsp;=&nbsp;", is_string($value) ? htmlSpecialChars($value) : Debug::dump($value, TRUE) ?><br>
			<?php endforeach ?>
			</code></td>
		</tr>
		<?php endforeach ?>
		</tbody>
		</table>
	<?php endif ?>
	</div>
</div>


<script type="text/javascript">
/* <![CDATA[ */
document.getElementById('routingDebuggerIcon').onclick = function(e) {
	var arrow = this.getElementsByTagName('abbr')[0];
	var panel = this.nextSibling;
	var collapsed = panel.currentStyle ? panel.currentStyle.display == 'none' : getComputedStyle(panel, null).display == 'none';

	arrow.innerHTML = collapsed ? String.fromCharCode(0x25bc) : String.fromCharCode(0x25ba);
	panel.style.display = collapsed ? 'block' : 'none';
	arrow.parentNode.style.position = collapsed ? 'absolute' : 'static';

	document.cookie = 'routingDebuggerVisible=' + collapsed*1 + '; path=/';
	return false;
}

document.body.appendChild(document.getElementById('routingDebugger'));

if (document.cookie.indexOf('routingDebuggerVisible=1') > -1) {
	document.getElementById('routingDebuggerIcon').onclick();
}
/* ]]> */
</script>
