<?php
// prolog Latte\Macros\CoreMacros
%A%
// prolog Nette\Bridges\ApplicationLatte\UIMacros

%A%
?>
Escaped: <?php echo Latte\Runtime\Filters::escapeHtml($hello, ENT_NOQUOTES) ?>


Non-escaped: <?php echo $hello ?>


<?php echo $hello ?>


<?php echo Latte\Runtime\Filters::escapeHtml($template->reverse($hello), ENT_NOQUOTES) ?>


<?php echo Latte\Runtime\Filters::escapeHtml($el, ENT_NOQUOTES) ?>
