<ul>
	<li><a href="{$component->link('add')}"><code>add</code></a> - link to view <em>add</em> in current presenter</li>
	<li><a href="{$component->link('Catalog:')}"><code>Catalog:</code></a> - link to presenter <em>Catalog</em> in current module and view <em>default</em></li>
	<li><a href="{$component->link('Export:Default:xml')}"><code>Export:Default:xml</code></a> - link to presenter <em>Default</em> in <em>Export</em> submodule and view <em>xml</em></li>
	<li><a href="{$component->link(':Admin:Default:')}"><code>:Admin:Default:</code></a> - link to presenter <em>Default</em> in <em>Admin</em> module (view <em>default</em>)</li>
</ul>