<?php

/**
 * Confirmation dialog which prevents Cross-Site Request Forgery (CSRF).
 * @param  array  $post
 * @param  string $question
 * @param  string $buttonCaption
 */


?>
<!DOCTYPE html>
<meta charset="utf-8">
<meta name=robots content=noindex>
<meta name=generator content="Nette Framework">
<style>
    body { color: #333; background: white; width: 600px; margin: 100px auto }
    h1 { font: bold 47px/1.5 sans-serif; margin: .6em 0 }
    p { font: 21px/1.5 Georgia,serif; margin: 1.5em 0 }
</style>

<title>Confirmation Required</title>

<h1>Confirmation Required</h1>

<p><?php echo htmlspecialchars($question ?: 'Are you sure you want to do this action?') ?></p>

<form action="" method="post">
	<p>
		<input type="submit" value="<?php echo htmlspecialchars($buttonCaption ?: 'Yes') ?>">
	</p>
	<?php foreach ($post as $key => $val): ?>
		<input type="hidden" name="<?php echo htmlspecialchars($key) ?>" value="<?php echo htmlspecialchars($val) ?>">
	<?php endforeach ?>
</form>

<p>If you did not request any action, do not click the button and leave this page immediately.</p>
