{**
 * My Application RSS feed template.
 *
 * @copyright  Copyright (c) 2009 John Doe
 * @package    MyApplication
 * @version    $Id$
 *
 * @param string   $title    feed title
 * @param string   $link     backlink
 * @param string   $description
 * @param array    $heads
 * @param array    $items
 *}

{contentType application/xml; charset=utf-8}
<<?php ?>?xml version="1.0"?>
<rss version="2.0">
	<channel>
		<title>{$title}</title>
		<link>{$link}</link>
		<description>{$description}</description>

		{foreach $heads as $key => $value}
		<{!$key}>{$value}</{!$key}>
		{/foreach}

		{foreach $items as $item}
		<item>
			{foreach $item as $key => $value}
			<{!$key}>{$value}</{!$key}>
			{/foreach}
		</item>
		{/foreach}
	</channel>
</rss>
