<?php

//

?><?php
// prolog Nette\Latte\Macros\CoreMacros
list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, 'xxx')
;
// prolog Nette\Latte\Macros\UIMacros

// snippets support
if (%A%}

//
// main template
//
?>
<p>Included file #2 (<?php echo Nette\Latte\Runtime\Filters::escapeHtml($localvar, ENT_NOQUOTES) ?>
, <?php echo Nette\Latte\Runtime\Filters::escapeHtml($hello, ENT_NOQUOTES) ?>)</p>
