<?php
// source: %a%

// prolog Nette\Latte\Macros\CoreMacros
list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, '%[a-z0-9]+%')
;
// prolog Nette\Latte\Macros\UIMacros

// snippets support
if (%A%}

//
// main template
//
?>

<?php ob_start(); $_l->templates['%[a-z0-9]+%']->renderChildTemplate('subdir/include1.latte', array('localvar' => 10) + $template->getParameters()); echo $template->indent(ob_get_clean()) ;
