<?php
// source: %a%

// prolog Nette\Latte\Macros\CoreMacros
list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, '%[a-z0-9]+%')
;
// prolog Nette\Bridges\CacheLatte\CacheMacro
Nette\Bridges\CacheLatte\CacheMacro::initRuntime($template, $_g);

// prolog Nette\Latte\Macros\UIMacros

// snippets support
if (%A%}

//
// main template
//
?>
Noncached content

<?php if (Nette\Bridges\CacheLatte\CacheMacro::createCache($netteCacheStorage, '%[a-z0-9]+%', $_g->caches, array($id, 'tags' => 'mytag'))) { ?>

<h1><?php echo Nette\Latte\Runtime\Filters::escapeHtml($template->upper($title), ENT_NOQUOTES) ?></h1>

<?php $_l->templates['%[a-z0-9]+%']->renderChildTemplate('include.cache.latte', array('localvar' => 11) + $template->getParameters()) ?>

<?php $_l->tmp = array_pop($_g->caches); if (!$_l->tmp instanceof stdClass) $_l->tmp->end(); }
