<?php list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, 'xxx')
;//
// block _outer
//
if (!function_exists($_l->blocks['_outer'][] = 'xxx')) { function _lxxx__outer($_l, $_args) { extract($_args); $control->validateControl('outer')
;$iterations = 0; foreach ($iterator = $_l->its[] = new Nette\Iterators\CachingIterator(array(1,2,3)) as $id): ?>
<div id="<?php echo $_dynSnippetId = $control->getSnippetId("inner-$id") ?>"><?php ob_start() ?>
                #<?php echo Nette\Templating\DefaultHelpers::escapeHtml($id, ENT_NOQUOTES) ?>

<?php $_dynSnippets[$_dynSnippetId] = ob_get_flush() ?>
</div><?php $iterations++; endforeach; array_pop($_l->its); $iterator = end($_l->its) ;if (isset($_dynSnippets)) return $_dynSnippets;
}}

//
// end of blocks
//

// template extending and snippets support

$_l->extends = empty($template->_extends) ? FALSE : $template->_extends; unset($_extends, $template->_extends);


if ($_l->extends) {
	ob_start();
} elseif (!empty($control->snippetMode)) {
	return Nette\Latte\Macros\UIMacros::renderSnippets($control, $_l, get_defined_vars());
}

//
// main template
//
?>
<div id="<?php echo $control->getSnippetId('outer') ?>"><?php call_user_func(reset($_l->blocks['_outer']), $_l, $template->getParams()) ?>
</div><?php
// template extending support
if ($_l->extends) {
	ob_end_clean();
	Nette\Latte\Macros\CoreMacros::includeTemplate($_l->extends, get_defined_vars(), $template)->render();
}