<?php

//

?><?php
// prolog Nette\Latte\Macros\CoreMacros
list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, 'xxx')
;
// prolog Nette\Latte\Macros\UIMacros
//
// block title
//
if (!function_exists($_l->blocks['title'][] = '_xxx_title')) { function _xxx_title($_l, $_args) { extract($_args)
?>My website<?php
}}

//
// block sidebar
//
if (!function_exists($_l->blocks['sidebar'][] = '_xxx_sidebar')) { function _xxx_sidebar($_l, $_args) { extract($_args)
?>		<ul>
			<li><a href="/">Homepage</a></li>
			<li><a href="/contact">Contact</a></li>
		</ul>
<?php
}}

//
// end of blocks
//

// template extending and snippets support

$_l->extends = empty($template->_extended) && isset($_control) && $_control instanceof Nette\Application\UI\Presenter ? $_control->findLayoutTemplateFile() : NULL; $template->_extended = $_extended = TRUE;


if ($_l->extends) {
	%A%}

//
// main template
//
extract(array('class' => NULL, 'namespace' => NULL, 'top' => TRUE), EXTR_SKIP) ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<link rel="stylesheet" href="style.css">
	<title><?php if ($_l->extends) { ob_end_clean(); return Nette\Latte\Macros\CoreMacros::includeTemplate($_l->extends, get_defined_vars(), $template)->render(); }
call_user_func(reset($_l->blocks['title']), $_l, get_defined_vars())  ?></title>
</head>

<body>
	<div id="sidebar">
<?php call_user_func(reset($_l->blocks['sidebar']), $_l, get_defined_vars())  ?>
	</div>

	<div id="content">
<?php Nette\Latte\Macros\UIMacros::callBlock($_l, 'content', $template->getParameters()) ?>
	</div>
</body>
</html>
