<?php
// prolog Nette\Latte\Macros\CoreMacros
list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, '%[a-z0-9]+%')
;
// prolog Nette\Latte\Macros\UIMacros

// snippets support
if (!empty($_control->snippetMode)) {
	return Nette\Latte\Macros\UIMacros::renderSnippets($_control, $_l, get_defined_vars());
}

//
// main template
//
?>
<span title=<?php echo '"' . Nette\Templating\Helpers::escapeHtml($x, ENT_COMPAT) . '"' ?>></span>

<span title=<?php echo '"' . Nette\Templating\Helpers::escapeHtml($x, ENT_COMPAT) . '"' ?>
 <?php echo '"' . Nette\Templating\Helpers::escapeHtml($x, ENT_COMPAT) . '"' ?>></span>
