<?php
// prolog Nette\Latte\Macros\CoreMacros
list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, 'xxx')
;
// prolog Nette\Latte\Macros\UIMacros
//
// block menu
//
if (!function_exists($_l->blocks['menu'][] = '_xxx_menu')) { function _xxx_menu($_l, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v
?><ul>
<?php $iterations = 0; foreach ($iterator = $_l->its[] = new Nette\Iterators\CachingIterator($menu) as $item) { ?>
	<li><?php echo Nette\Templating\Helpers::escapeHtml($counter++, ENT_NOQUOTES) ?>
 <?php if (is_array($item)) { ?> <?php call_user_func(reset($_l->blocks['menu']), $_l, array('menu' => $item) + get_defined_vars()) ?>
 <?php } else { echo Nette\Templating\Helpers::escapeHtml($item, ENT_NOQUOTES) ;} ?></li>
<?php $iterations++; } array_pop($_l->its); $iterator = end($_l->its) ?>
</ul>
<?php
}}

//
// block bl
//
if (!function_exists($_l->blocks['bl'][] = '_xxx_bl')) { function _xxx_bl($_l, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v
?><ul title="block + if + foreach">
<?php $iterations = 0; foreach ($people as $person) { if (strlen($person)===4) { ?>
	<li><?php echo Nette\Templating\Helpers::escapeHtml($person, ENT_NOQUOTES) ?></li>
<?php } $iterations++; } ?>
</ul>
<?php
}}

//
// end of blocks
//

// template extending and snippets support

$_l->extends = empty($template->_extended) && isset($_control) && $_control instanceof Nette\Application\UI\Presenter ? $_control->findLayoutTemplateFile() : NULL; $template->_extended = $_extended = TRUE;


if ($_l->extends) {
	ob_start();

} elseif (!empty($_control->snippetMode)) {
	return Nette\Latte\Macros\UIMacros::renderSnippets($_control, $_l, get_defined_vars());
}

//
// main template
//
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ul>
	<li>Escaped: <?php echo Nette\Templating\Helpers::escapeHtml($hello, ENT_NOQUOTES) ?></li>
	<li>Non-escaped: <?php echo $hello ?></li>
	<li>Escaped expression: <?php echo Nette\Templating\Helpers::escapeHtml('<' . 'b' . '>hello' . '</b>', ENT_NOQUOTES) ?></li>
	<li>Non-escaped expression: <?php echo '<' . 'b' . '>hello' . '</b>' ?></li>
	<li>Array access: <?php echo Nette\Templating\Helpers::escapeHtml($people[1], ENT_NOQUOTES) ?></li>
	<li>Html: <?php echo Nette\Templating\Helpers::escapeHtml($el, ENT_NOQUOTES) ?></li>
	<li>Translated: <?php echo Nette\Templating\Helpers::escapeHtml($template->translate($people[1]), ENT_NOQUOTES) ?></li>
	<li>Translated string: <?php echo Nette\Templating\Helpers::escapeHtml($template->translate('ahoj'), ENT_NOQUOTES) ?></li>
	<li>Non-escaped and translated: <?php echo $template->translate($people[1]) ?></li>
	<li>Condition: <?php echo Nette\Templating\Helpers::escapeHtml($hello ? 'yes' : NULL, ENT_NOQUOTES) ?>
 <?php echo Nette\Templating\Helpers::escapeHtml($hello ? 'yes' : NULL, ENT_NOQUOTES) ?></li>
	<li>Array: <?php echo Nette\Templating\Helpers::escapeHtml($template->join($hello ? array('a', 'b', 'c') : NULL), ENT_NOQUOTES) ?>
 <?php echo Nette\Templating\Helpers::escapeHtml($template->join(array('a', 'b', $hello ? 'c' : NULL)), ENT_NOQUOTES) ?></li>
</ul>

<input> <input> <input>

<input checked> <input checked="checked">

{ test} {"test} {'test}

<p<?php echo Nette\Utils\Html::el(NULL, array('title' => $hello, 'lang' => isset($lang) ? $lang : NULL))->attributes() ?>> </p>

<p val = <?php if (true) { ?>"a"<?php } else { ?>"b"<?php } ?>> </p>

<p val0 val1 = tmp val2=tmp val3="x"></p> </p>

<p val = <?php echo '"' . htmlSpecialChars($xss) . '"' ?>> </p>

<p onclick = <?php echo '"' . htmlSpecialChars(Nette\Templating\Helpers::escapeJs($xss)) . '"' ?>> </p>

<p ONCLICK ="<?php echo htmlSpecialChars(Nette\Templating\Helpers::escapeJs($xss)) ?>
" <?php echo '"' . htmlSpecialChars($xss) . '"' ?>> </p>

<p val =></p><?php echo Nette\Templating\Helpers::escapeHtml($xss, ENT_NOQUOTES) ?></p>

<?php echo Nette\Templating\Helpers::escapeHtml((string) (bool) (float) (int) (array) 10, ENT_NOQUOTES) ?>


<?php if ($hello) { ?>
	<?php echo Nette\Templating\Helpers::escapeHtml($hello, ENT_NOQUOTES) ?>

<?php } elseif ($any) { ?>
	<?php echo Nette\Templating\Helpers::escapeHtml($any, ENT_NOQUOTES) ?>

<?php } else { ?>
	none
<?php } ?>


<?php $iterations = 0; foreach ($iterator = $_l->its[] = new Nette\Iterators\CachingIterator(array(TRUE)) as $foo) { $iterations = 0; foreach ($iterator = $_l->its[] = new Nette\Iterators\CachingIterator($people) as $person) { ?>
	<?php if ($iterator->isFirst()) { ?><ul><?php } ?>

	<li id="item-<?php echo htmlSpecialChars($iterator->getCounter()) ?>" class="<?php echo htmlSpecialChars($iterator->isOdd() ? 'odd' : 'even') ?>
"><?php echo Nette\Templating\Helpers::escapeHtml($person, ENT_NOQUOTES) ?></li>
	<?php if ($iterator->isLast()) { ?></ul><?php } ?>

<?php $iterations++; } array_pop($_l->its); $iterator = end($_l->its) ;$iterations++; } array_pop($_l->its); $iterator = end($_l->its) ?>



<STYLE type="text/css">
<!--
#<?php echo Nette\Templating\Helpers::escapeCss($xss) ?> {
	background: blue;
}
-->
</style>



<script>
<!--
alert('</div>');

var prop = <?php echo Nette\Templating\Helpers::escapeJs($people) ?>;

document.getElementById(<?php echo Nette\Templating\Helpers::escapeJs($xss) ?>).style.backgroundColor = 'red';

var html = <?php echo Nette\Templating\Helpers::escapeJs($el) ?>;
-->
</script>


<SCRIPT>
/* <![CDATA[ */

var prop2 = <?php echo Nette\Templating\Helpers::escapeJs($people) ?>;

/* ]]> */
</script>


<p onclick =
'alert(<?php echo htmlSpecialChars(Nette\Templating\Helpers::escapeJs($xss), ENT_QUOTES) ?>);alert("hello");'
 title='<?php echo htmlSpecialChars($xss, ENT_QUOTES) ?>'
 STYLE =
 "color:<?php echo htmlSpecialChars(Nette\Templating\Helpers::escapeCss($xss)) ?>;"
 rel="<?php echo htmlSpecialChars($xss) ?>"
 onblur="alert(<?php echo htmlSpecialChars(Nette\Templating\Helpers::escapeJs($xss)) ?>)"
 alt='<?php echo htmlSpecialChars($el, ENT_QUOTES) ?>'
 onfocus="alert(<?php echo htmlSpecialChars(Nette\Templating\Helpers::escapeJs($el)) ?>)"
>click on me <?php echo Nette\Templating\Helpers::escapeHtml($xss, ENT_NOQUOTES) ?></p>



<?php $counter = 0 ;if ($_l->extends) { ob_end_clean(); return Nette\Latte\Macros\CoreMacros::includeTemplate($_l->extends, get_defined_vars(), $template)->render(); }
call_user_func(reset($_l->blocks['menu']), $_l, get_defined_vars())  ?>


<?php extract(array('varx' => 2), EXTR_SKIP) ;echo Nette\Templating\Helpers::escapeHtml($varx, ENT_NOQUOTES) ?>

<?php extract(array('varx' => 4), EXTR_SKIP) ;echo Nette\Templating\Helpers::escapeHtml($varx, ENT_NOQUOTES) ?>


<?php $varx = 8 ;echo Nette\Templating\Helpers::escapeHtml($varx, ENT_NOQUOTES) ?>

<?php $varx = 9 ;echo Nette\Templating\Helpers::escapeHtml($varx, ENT_NOQUOTES) ?>


<?php $now = new DateTime ;$foo = $now->format('u') ;extract(array('foo' => $now->format('u')), EXTR_SKIP) ?>



</ul>


<ul title="foreach">
<?php $iterations = 0; foreach ($people as $person) { ?>	<li><?php echo Nette\Templating\Helpers::escapeHtml($person, ENT_NOQUOTES) ?></li>
<?php $iterations++; } ?>
</ul>

<ul title="for">
<?php for ($i=0;$i<3;$i++) { ?>	<li><?php echo Nette\Templating\Helpers::escapeHtml($i, ENT_NOQUOTES) ?></li>
<?php } ?>
</ul>

<ul title="white">
<?php while (--$i>0) { ?>	<li><?php echo Nette\Templating\Helpers::escapeHtml($i, ENT_NOQUOTES) ?></li>
<?php } ?>
</ul>

<?php if (true) { ?><p>
	<div><p>true</div>
</p>
<?php } ?>

<?php if (true) { ?><p>
	<div><p>true</p></div>
</p>
<?php } ?>

<?php if (false) { ?><p>
	<div><p>false</div>
</p>
<?php } ?>

<?php if (false) { ?><p>
	<div><p>false</p></div>
</p>
<?php } ?>

<?php if (strlen('{$xss}') > 5) { ?><p>noLatte</p>
<?php } ?>

<ul title="if + foreach">
<?php $iterations = 0; foreach ($people as $person) { if (strlen($person)===4) { ?>
	<li><?php echo Nette\Templating\Helpers::escapeHtml($person, ENT_NOQUOTES) ?></li>
<?php } $iterations++; } ?>
</ul>

<ul title="if + inner-if + inner-foreach">
<?php if (empty($iterator)) { ?>	<li><?php $iterations = 0; foreach ($people as $person) { if (strlen($person)===4) { echo Nette\Templating\Helpers::escapeHtml($person, ENT_NOQUOTES) ;} $iterations++; } ?></li>
<?php } ?>
</ul>

<ul title="inner-if + inner-foreach">
<?php $iterations = 0; foreach ($people as $person) { if (strlen($person)===4) { ?>
	<li><?php echo Nette\Templating\Helpers::escapeHtml($template->lower($person), ENT_NOQUOTES) ?></li>
<?php } $iterations++; } ?></ul>

<?php call_user_func(reset($_l->blocks['bl']), $_l, get_defined_vars())  ?>

<?php if ($_l->ifs[] = (true)) { ?><b><?php } ?>
bold<?php if (array_pop($_l->ifs)) { ?></b><?php } ?>
 <?php if ($_l->ifs[] = (false)) { ?><b><?php } ?>
normal<?php if (array_pop($_l->ifs)) { ?></b>
<?php } ?>

<?php if ($_l->ifs[] = (true)) { ?><b<?php if ($_l->tmp = array_filter(array('first'))) echo ' class="' . htmlSpecialChars(implode(" ", array_unique($_l->tmp))) . '"' ?>
><?php } ?>
bold<?php if (array_pop($_l->ifs)) { ?></b>
<?php } ?>

<?php echo 'test' ?>


{ }

<p<?php if ($_l->tmp = array_filter(array('foo', (false ? 'first' : NULL), 'odd', ($hello ? 'foo' : 'bar')))) echo ' class="' . htmlSpecialChars(implode(" ", array_unique($_l->tmp))) . '"' ?>>n:class</p>

<p<?php if ($_l->tmp = array_filter(array(false ? 'first' : NULL))) echo ' class="' . htmlSpecialChars(implode(" ", array_unique($_l->tmp))) . '"' ?>>n:class empty</p>

<meta>
<?php if (true) { ?><meta>
<?php } if ($_l->ifs[] = (true)) { ?><meta>
<?php } if (array_pop($_l->ifs)) { } ?>
<meta>
<?php if (true) { } ?><meta>

<?php ob_start() ?>TRUE<?php if (TRUE) ob_end_flush(); else ob_end_clean() ?>

<?php ob_start() ?>FALSE<?php if (FALSE) ob_end_flush(); else ob_end_clean() ?>

<?php ob_start() ?>TRUE<?php ob_start() ?>FALSE<?php if (TRUE) { ob_end_clean(); ob_end_flush(); } else { $_else = ob_get_contents(); ob_end_clean(); ob_end_clean(); echo $_else; } ?>


<?php $iterations = 0; foreach ($iterator = $_l->its[] = new Nette\Iterators\CachingIterator(array(1,2,3)) as $foo) { ?>
	<b<?php if ($_l->tmp = array_filter(array($iterator->even ? 'even' : NULL))) echo ' class="' . htmlSpecialChars(implode(" ", array_unique($_l->tmp))) . '"' ?>>item</b>
<?php $iterations++; } array_pop($_l->its); $iterator = end($_l->its) ?>

<?php $iterations = 0; foreach ($iterator = $_l->its[] = new Nette\Iterators\CachingIterator(array(1, 2, 3)) as $foo) { ?>
<p<?php if ($_l->tmp = array_filter(array($iterator->even ? 'even' : NULL))) echo ' class="' . htmlSpecialChars(implode(" ", array_unique($_l->tmp))) . '"' ?>
><?php echo Nette\Templating\Helpers::escapeHtml($foo, ENT_NOQUOTES) ?></p>
<?php $iterations++; } array_pop($_l->its); $iterator = end($_l->its) ?>

<?php $iterations = 0; foreach (array(0) as $foo) { if (1) { $iterations = 0; foreach (array(1) as $foo) { if ($_l->ifs[] = (0)) { ?>
<span><?php } $iterations++; } $iterations = 0; foreach (array(2) as $foo) { if (2) { ?>
Hello<?php } $iterations++; } $iterations = 0; foreach (array(1) as $foo) { if (array_pop($_l->ifs)) { ?></span>
<?php } $iterations++; } } $iterations++; } ?>


<ul title="foreach break">
<?php $iterations = 0; foreach ($people as $person) { ?>	<li><?php echo Nette\Templating\Helpers::escapeHtml($person, ENT_NOQUOTES) ;if (TRUE) { echo "</li>\n"; break; } ?></li>
<?php $iterations++; } ?>
</ul>

<ul title="foreach continue">
<?php $iterations = 0; foreach ($people as $person) { ?>	<li><?php echo Nette\Templating\Helpers::escapeHtml($person, ENT_NOQUOTES) ;if (TRUE) { echo "</li>\n"; continue; } ?></li>
<?php $iterations++; } ?>
</ul>


<ul title="inner foreach break">
	<li><?php $iterations = 0; foreach ($people as $person) { echo Nette\Templating\Helpers::escapeHtml($person, ENT_NOQUOTES) ;if (TRUE) break ;$iterations++; } ?></li>
</ul>

<ul title="inner foreach continue">
	<li><?php $iterations = 0; foreach ($people as $person) { echo Nette\Templating\Helpers::escapeHtml($person, ENT_NOQUOTES) ;if (TRUE) continue ;$iterations++; } ?></li>
</ul>
