<?php
// prolog Nette\Latte\Macros\CoreMacros
list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, 'xxx')
;
// prolog Nette\Latte\Macros\UIMacros
//
// block content
//
if (!function_exists($_l->blocks['content'][] = '_xxx_content')) { function _xxx_content($_l, $_args) { extract($_args)
?>
	<h1><?php call_user_func(reset($_l->blocks['title']), $_l, get_defined_vars())  ?></h1>

	<ul>
<?php $iterations = 0; foreach ($iterator = $_l->its[] = new Nette\Iterators\CachingIterator($people) as $person): ?>
		<li><?php echo Nette\Templating\Helpers::escapeHtml($person, ENT_NOQUOTES) ?></li>
<?php $iterations++; endforeach; array_pop($_l->its); $iterator = end($_l->its) ?>
	</ul>
<?php
}}

//
// block title
//
if (!function_exists($_l->blocks['title'][] = '_xxx_title')) { function _xxx_title($_l, $_args) { extract($_args)
?>Homepage<?php
}}

//
// block sidebar
//
if (!function_exists($_l->blocks['sidebar'][] = '_xxx_sidebar')) { function _xxx_sidebar($_l, $_args) { extract($_args)
;
}}

//
// end of blocks
//

// template extending and snippets support

$_l->extends = true; unset($_extends, $template->_extends);


if ($_l->extends) {
	ob_start();
} elseif (%A%}

//
// main template
//
$_l->extends = "inheritance.parent.latte" ?>





<?php
// epilog Nette\Latte\Macros\UIMacros

// template extending support
if ($_l->extends) {
	ob_end_clean();
	Nette\Latte\Macros\CoreMacros::includeTemplate($_l->extends, get_defined_vars(), $template)->render();
}
