<?php
// prolog Nette\Latte\Macros\CoreMacros
list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, 'xxx')
;
// prolog Nette\Latte\Macros\UIMacros
//
// block test
//
if (!function_exists($_l->blocks['test'][] = '_xxx_test')) { function _xxx_test($_l, $_args) { extract($_args)
?>	This is definition #<?php echo Nette\Templating\Helpers::escapeHtml($var, ENT_NOQUOTES) ?>

<?php
}}

//
// end of blocks
//

// template extending and snippets support

$_l->extends = empty($template->_extended) && isset($_control) && $_control instanceof Nette\Application\UI\Presenter ? $_control->findLayoutTemplateFile() : NULL; $template->_extended = $_extended = TRUE;


if ($_l->extends) {
	%A%}

//
// main template
//
?>

<?php $var = 10 ?>

<?php if ($_l->extends) { ob_end_clean(); return Nette\Latte\Macros\CoreMacros::includeTemplate($_l->extends, get_defined_vars(), $template)->render(); } ?>

<?php call_user_func(reset($_l->blocks['test']), $_l, array('var' => 20) + get_defined_vars()) ;
