<?php
// source: %a%

// prolog Latte\Macros\CoreMacros
list($_l, $_g) = Latte\Macros\CoreMacros::initRuntime($template, '%[a-z0-9]+%')
;
//
// main template
//
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ul>
<?php $iterations = 0; foreach ($people as $person) { ?>
	<li><?php echo Latte\Runtime\Filters::escapeHtml($template->upper($person), ENT_NOQUOTES) ?></li>
<?php $iterations++; } ?>
{* comment latte *}
</ul>

<p>Default: <?php echo Latte\Runtime\Filters::escapeHtml($person, ENT_NOQUOTES) ?></p>

<ul>
<?php $iterations = 0; foreach ($people as $person) { ?>
	<li><?php echo Latte\Runtime\Filters::escapeHtml($template->upper($person), ENT_NOQUOTES) ?></li>
<?php $iterations++; } ?>
</ul>

<p>Default: <?php echo Latte\Runtime\Filters::escapeHtml($person, ENT_NOQUOTES) ?></p>

<ul>
<?php $iterations = 0; foreach ($people as $person) { ?>
	<li><?php echo Latte\Runtime\Filters::escapeHtml($template->upper($person), ENT_NOQUOTES) ?></li>
<?php $iterations++; } ?>
</ul>

<p>Default: <?php echo Latte\Runtime\Filters::escapeHtml($person, ENT_NOQUOTES) ?></p>

<p>Default: <?php echo Latte\Runtime\Filters::escapeHtml($person, ENT_NOQUOTES) ?></p>

<p>Default: {$person}</p>
