<?php

//

?><?php list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, 'xxx')
;
// snippets support
if (%A%}

//
// main template
//
?>
<ul>
<?php $iterations = 0; foreach ($iterator = $_l->its[] = new Nette\Iterators\CachingIterator($menu) as $item): ?>
	<li><?php if (is_array($item)): ?> <?php Nette\Latte\Macros\CoreMacros::includeTemplate('@menu.latte', array('menu' => $item) + $template->getParameters(), $_l->templates['xxx'])->render() ?>
 <?php else: echo Nette\Templating\Helpers::escapeHtml($item, ENT_NOQUOTES) ;endif ?></li>
<?php $iterations++; endforeach; array_pop($_l->its); $iterator = end($_l->its) ?>
</ul>
