<?php
// prolog Nette\Latte\Macros\CoreMacros
list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, 'xxx')
;
// prolog Nette\Latte\Macros\UIMacros

// snippets support
if (%A%}

//
// main template
//
?>

<?php Nette\Latte\Macros\CoreMacros::includeTemplate('includeblock.inc.latte', get_defined_vars(), $_l->templates['xxx'])->render() ?>

<?php Nette\Latte\Macros\UIMacros::callBlock($_l, 'test', $template->getParameters()) ;
