<?php

//

?><?php
// prolog Nette\Latte\Macros\CoreMacros
list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, 'xxx')
;
// prolog Nette\Latte\Macros\CacheMacro
Nette\Latte\Macros\CacheMacro::initRuntime($template, $_g);

// prolog Nette\Latte\Macros\UIMacros

// snippets support
if (%A%}

//
// main template
//
?>
<p>Included file (<?php echo Nette\Templating\Helpers::escapeHtml($localvar, ENT_NOQUOTES) ?>)</p>

<?php if (Nette\Latte\Macros\CacheMacro::createCache($netteCacheStorage, 'xxx', $_g->caches)) { ?>
	<?php echo Nette\Templating\Helpers::escapeHtml($template->lower($title), ENT_NOQUOTES) ?>

<?php $_l->tmp = array_pop($_g->caches); if (!$_l->tmp instanceof stdClass) $_l->tmp->end(); }
