<?php

//

?><?php list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, 'xxx')
;
// snippets support
if (isset($presenter, $control) && $presenter->isAjax() && $control->isControlInvalid()) {
	return Nette\Latte\Macros\UIMacros::renderSnippets($control, $_l, get_defined_vars());
}

//
// main template
//
?>
<p>Included file #3 (<?php echo Nette\Templating\DefaultHelpers::escapeHtml($localvar, ENT_NOQUOTES) ?>
, <?php echo Nette\Templating\DefaultHelpers::escapeHtml($hello, ENT_NOQUOTES) ?>)</p>
