<?php list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, 'xxx')
;//
// block test
//
if (!function_exists($_l->blocks['test'][] = 'xxx')) { function _lxxx_test($_l, $_args) { extract($_args)
?>
	This is definition #<?php echo Nette\Templating\DefaultHelpers::escapeHtml($var, ENT_NOQUOTES) ?>

<?php
}}

//
// end of blocks
//

// template extending and snippets support

$_l->extends = empty($template->_extends) ? FALSE : $template->_extends; unset($_extends, $template->_extends);


if ($_l->extends) {
	ob_start();
} elseif (%A%}

//
// main template
//
?>

<?php $var = 10 ?>


<?php call_user_func(reset($_l->blocks['test']), $_l, array('var' => 20) + $template->getParams()) ;
// template extending support
if ($_l->extends) {
	ob_end_clean();
	Nette\Latte\Macros\CoreMacros::includeTemplate($_l->extends, get_defined_vars(), $template)->render();
}
