<?php
// source: %a%

// prolog Latte\Macros\CoreMacros
list($_l, $_g) = Latte\Macros\CoreMacros::initRuntime($template, '%[a-z0-9]+%')
;
//
// main template
//
?>
<p>Included file #1</p>

<?php $_l->templates['%[a-z0-9]+%']->renderChildTemplate("include2.latte", array('localvar' => 20) + $template->getParameters()) ?>

<?php $_l->templates['%[a-z0-9]+%']->renderChildTemplate("../include3.latte", $template->getParameters()) ?>

<textarea>
pre
</textarea>
