<?php
// prolog Nette\Latte\Macros\CoreMacros
list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, '%[a-z0-9]+%')
;
// prolog Nette\Latte\Macros\UIMacros

// snippets support
if (%A%}

//
// main template
//
?>

<?php echo $template->indent(Nette\Latte\Macros\CoreMacros::includeTemplate('subdir/include1.latte', array('localvar' => 10) + $template->getParameters(), $_l->templates['%[a-z0-9]+%'])->__toString(TRUE)) ?>
