<?php
// prolog Nette\Latte\Macros\CoreMacros
list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, '%[a-z0-9]+%')
;
// prolog Nette\Latte\Macros\UIMacros

// snippets support
if (%A%}

//
// main template
//
$netteHttpResponse->setHeader("Content-Type", 'text/calendar; charset=utf-8') ;$start = '2011-06-06'; $end = '2011-06-07'; $info = "Hello \"hello\", \nWorld" ?>
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//example.org//iCal 4.0.3//CS
METHOD:PUBLISH
BEGIN:VEVENT
DTSTAMP:<?php echo Nette\Latte\Runtime\Filters::escapeIcal($template->date($start, 'Ymd\THis')) ?>

DTSTART;TZID=Europe/Prague:<?php echo Nette\Latte\Runtime\Filters::escapeIcal($template->date($start, 'Ymd\THis')) ?>

DTEND;TZID=Europe/Prague:<?php echo Nette\Latte\Runtime\Filters::escapeIcal($template->date($end, 'Ymd\THis')) ?>

SUMMARY;LANGUAGE=cs:<?php echo Nette\Latte\Runtime\Filters::escapeIcal($info) ?>

DESCRIPTION:
CLASS:PUBLIC
END:VEVENT
END:VCALENDAR
