<?php
// source: %a%

// prolog Nette\Latte\Macros\CoreMacros
list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, '%[a-z0-9]+%')
;
// prolog Nette\Latte\Macros\BlockMacros
//
// block title
//
if (!function_exists($_l->blocks['title'][] = '_%[a-z0-9]+%_title')) { function _%[a-z0-9]+%_title($_l, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v
?>Homepage | <?php Nette\Latte\Macros\BlockMacros::callBlockParent($_l, 'title', get_defined_vars()) ;
}}

//
// block content
//
if (!function_exists($_l->blocks['content'][] = '_%[a-z0-9]+%_content')) { function _%[a-z0-9]+%_content($_l, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v
?>	<ul>
<?php $iterations = 0; foreach ($people as $person) { ?>
		<li><?php echo Nette\Latte\Runtime\Filters::escapeHtml($person, ENT_NOQUOTES) ?></li>
<?php $iterations++; } ?>
	</ul>
<?php
}}

//
// end of blocks
//

// template extending

$_l->extends = "inheritance.parent.latte"; $template->_extended = $_extended = TRUE;

if ($_l->extends) { ob_start();}

//
// main template
// ?>

<?php if ($_l->extends) { ob_end_clean(); return $template->renderChildTemplate($_l->extends, get_defined_vars()); }
call_user_func(reset($_l->blocks['title']), $_l, get_defined_vars())  ?>


<?php call_user_func(reset($_l->blocks['content']), $_l, get_defined_vars()) ;
