<?php
// prolog Nette\Latte\Macros\CoreMacros
list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, 'xxx')
;
// prolog Nette\Latte\Macros\UIMacros
//
// block content
//
if (!function_exists($_l->blocks['content'][] = '_xxx_content')) { function _xxx_content($_l, $_args) { extract($_args)
?>	<h1><?php call_user_func(reset($_l->blocks['title']), $_l, get_defined_vars())  ?></h1>

	<ul>
<?php $iterations = 0; foreach ($people as $person): ?>
		<li><?php echo Nette\Templating\Helpers::escapeHtml($person, ENT_NOQUOTES) ?></li>
<?php $iterations++; endforeach ?>
	</ul>
<?php
}}

//
// block title
//
if (!function_exists($_l->blocks['title'][] = '_xxx_title')) { function _xxx_title($_l, $_args) { extract($_args)
?>Homepage<?php
}}

//
// block sidebar
//
if (!function_exists($_l->blocks['sidebar'][] = '_xxx_sidebar')) { function _xxx_sidebar($_l, $_args) { extract($_args)
;
}}

//
// end of blocks
//

// template extending and snippets support

$_l->extends = "inheritance.parent.latte"; $template->_extended = $_extended = TRUE;


if ($_l->extends) {
	%A%}

//
// main template
// ?>


<?php if ($_l->extends) { ob_end_clean(); return Nette\Latte\Macros\CoreMacros::includeTemplate($_l->extends, get_defined_vars(), $template)->render(); }
call_user_func(reset($_l->blocks['content']), $_l, get_defined_vars())  ?>


<?php call_user_func(reset($_l->blocks['sidebar']), $_l, get_defined_vars())  ?>
