%A%
// block _
//
if (!function_exists($_l->blocks['_'][] = '_%[a-z0-9]+%__')) { function _%[a-z0-9]+%__($_l, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v; $_control->redrawControl(false, FALSE)
;
}}

//
// block _outer
//
if (!function_exists($_l->blocks['_outer'][] = '_%[a-z0-9]+%__outer')) { function _%[a-z0-9]+%__outer($_l, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v; $_control->redrawControl('outer', FALSE)
?>	Outer
		<div id="<?php echo $_control->getSnippetId('inner') ?>"><?php call_user_func(reset($_l->blocks['_inner']), $_l, $template->getParameters()) ?>
</div>
	/Outer
<?php
}}

//
// block _inner
//
if (!function_exists($_l->blocks['_inner'][] = '_%[a-z0-9]+%__inner')) { function _%[a-z0-9]+%__inner($_l, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v; $_control->redrawControl('inner', FALSE)
?>Inner<?php
}}

//
// block _title
//
if (!function_exists($_l->blocks['_title'][] = '_%[a-z0-9]+%__title')) { function _%[a-z0-9]+%__title($_l, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v; $_control->redrawControl('title', FALSE)
?>Title 1<?php
}}

//
// block _title2
//
if (!function_exists($_l->blocks['_title2'][] = '_%[a-z0-9]+%__title2')) { function _%[a-z0-9]+%__title2($_l, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v; $_control->redrawControl('title2', FALSE)
?>Title 2<?php
}}

//
// end of blocks
%A%
	return Nette\Latte\Macros\UIMacros::renderSnippets($_control, $_l, get_defined_vars());
%A%
<div id="<?php echo $_control->getSnippetId('') ?>"><?php call_user_func(reset($_l->blocks['_']), $_l, $template->getParameters()) ?>
</div>


<div id="<?php echo $_control->getSnippetId('outer') ?>"><?php call_user_func(reset($_l->blocks['_outer']), $_l, $template->getParameters()) ?>
</div>


	@<?php if (true) { ?> Hello World @<?php } ?>


	<h2 id="<?php echo $_control->getSnippetId('title') ?>"><?php call_user_func(reset($_l->blocks['_title']), $_l, $template->getParameters()) ?>
</h2>

	<h2 id="<?php echo $_control->getSnippetId('title2') ?>"><?php call_user_func(reset($_l->blocks['_title2']), $_l, $template->getParameters()) ?>
</h2>
