<?php
// source: %a%

// prolog Nette\Latte\Macros\CoreMacros
list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, '%[a-z0-9]+%')
;
// prolog Nette\Latte\Macros\BlockMacros
//
// block test
//
if (!function_exists($_l->blocks['test'][] = '_%[a-z0-9]+%_test')) { function _%[a-z0-9]+%_test($_l, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v
?>	This is definition #<?php echo Nette\Latte\Runtime\Filters::escapeHtml($var, ENT_NOQUOTES) ?>

<?php
}}

//
// end of blocks
//

// template extending

$_l->extends = empty($template->_extended) && isset($_control) && $_control instanceof Nette\Application\UI\Presenter ? $_control->findLayoutTemplateFile() : NULL; $template->_extended = $_extended = TRUE;

if ($_l->extends) { ob_start();}

//
// main template
//
?>

<?php $var = 10 ?>

<?php if ($_l->extends) { ob_end_clean(); return $template->renderChildTemplate($_l->extends, get_defined_vars()); } ?>

<?php call_user_func(reset($_l->blocks['test']), $_l, array('var' => 20) + get_defined_vars()) ;
