%A%
// block _
//
if (!function_exists($_l->blocks['_'][] = '%a%__')) { function %a%__($_l, $_args) { extract($_args); $control->validateControl(false)
?>

<?php
}}

//
// block _outer
//
if (!function_exists($_l->blocks['_outer'][] = '%a%__outer')) { function %a%__outer($_l, $_args) { extract($_args); $control->validateControl('outer')
?>
	Outer
		<div id="<?php echo $control->getSnippetId('inner') ?>"><?php call_user_func(reset($_l->blocks['_inner']), $_l, $template->getParams()) ?>
</div>
	/Outer
<?php
}}

//
// block _inner
//
if (!function_exists($_l->blocks['_inner'][] = '%a%__inner')) { function %a%__inner($_l, $_args) { extract($_args); $control->validateControl('inner')
?>Inner<?php
}}

//
// block _title
//
if (!function_exists($_l->blocks['_title'][] = '%a%__title')) { function %a%__title($_l, $_args) { extract($_args); $control->validateControl('title')
?>Title 1<?php
}}

//
// block _title2
//
if (!function_exists($_l->blocks['_title2'][] = '%a%__title2')) { function %a%__title2($_l, $_args) { extract($_args); $control->validateControl('title2')
?>Title 2<?php
}}

//
// end of blocks
%A%
	return Nette\Latte\Macros\UIMacros::renderSnippets($control, $_l, get_defined_vars());
%A%
<div id="<?php echo $control->getSnippetId('') ?>"><?php call_user_func(reset($_l->blocks['_']), $_l, $template->getParams()) ?>
</div>


<div id="<?php echo $control->getSnippetId('outer') ?>"><?php call_user_func(reset($_l->blocks['_outer']), $_l, $template->getParams()) ?>
</div>


	@<?php if (true): ?> Hello World @<?php endif ?>


	<h2 id="<?php echo $control->getSnippetId('title') ?>"><?php call_user_func(reset($_l->blocks['_title']), $_l, $template->getParams()) ?>
</h2>

	<h2 id="<?php echo $control->getSnippetId('title2') ?>"><?php call_user_func(reset($_l->blocks['_title2']), $_l, $template->getParams()) ?>
</h2>
%A%
