<?php
// source: %a%

// prolog Nette\Latte\Macros\CoreMacros
list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, '%[a-z0-9]+%')
;
// prolog Nette\Latte\Macros\UIMacros
//
// block _outer
//
if (!function_exists($_l->blocks['_outer'][] = '_%[a-z0-9]+%__outer')) { function _%[a-z0-9]+%__outer($_l, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v; $_control->redrawControl('outer', FALSE)
?>	<p>Outer</p>
<?php
}}

//
// block _inner
//
if (!function_exists($_l->blocks['_inner'][] = '_%[a-z0-9]+%__inner')) { function _%[a-z0-9]+%__inner($_l, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v; $_control->redrawControl('inner', FALSE)
?>	<p>Inner</p>
<?php
}}

//
// block _gallery
//
if (!function_exists($_l->blocks['_gallery'][] = '_%[a-z0-9]+%__gallery')) { function _%[a-z0-9]+%__gallery($_l, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v; $_control->redrawControl('gallery', FALSE)
;
}}

//
// end of blocks
//

// template extending and snippets support

$_l->extends = empty($template->_extended) && isset($_control) && $_control instanceof Nette\Application\UI\Presenter ? $_control->findLayoutTemplateFile() : NULL; $template->_extended = $_extended = TRUE;


if ($_l->extends) {
	ob_start();

} elseif (!empty($_control->snippetMode)) {
	return Nette\Latte\Macros\UIMacros::renderSnippets($_control, $_l, get_defined_vars());
}

//
// main template
//
?>	<div class="test"<?php echo ' id="' . $_control->getSnippetId('outer') . '"' ?>>
<?php if ($_l->extends) { ob_end_clean(); return $template->renderChildTemplate($_l->extends, get_defined_vars()); }
call_user_func(reset($_l->blocks['_outer']), $_l, $template->getParameters()) ?>
	</div>

	<div class="test"<?php echo ' id="' . $_control->getSnippetId('inner') . '"' ?>>
<?php call_user_func(reset($_l->blocks['_inner']), $_l, $template->getParameters())  ?>	</div>

	<div class="<?php echo htmlSpecialChars('class') ?>"<?php echo ' id="' . $_control->getSnippetId('gallery') . '"' ?>
><?php call_user_func(reset($_l->blocks['_gallery']), $_l, $template->getParameters()) ?>
</div>
