<?php list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, 'xxx')
;//
// block static
//
if (!function_exists($_l->blocks['static'][] = 'xxx')) { function _lxxx_static($_l, $_args) { extract($_args)
?>
	Static block #<?php echo Nette\Templating\DefaultHelpers::escapeHtml($var, ENT_NOQUOTES) ?>

<?php
}}

//
// end of blocks
//

// template extending and snippets support

$_l->extends = empty($template->_extends) ? FALSE : $template->_extends; unset($_extends, $template->_extends);


if ($_l->extends) {
	ob_start();
} elseif (%A%}

//
// main template
//
$var = 10 ?>

<?php if (!$_l->extends) { call_user_func(reset($_l->blocks['static']), $_l, get_defined_vars()); } ?>



<?php $iterations = 0; foreach ($iterator = $_l->its[] = new Nette\Iterators\CachingIterator(array('dynamic', 'static')) as $name): //
// block $name
//
if (!function_exists($_l->blocks[$name][] = 'xxx')) { function _lxxx__name($_l, $_args) { extract($_args) ?>
		Dynamic block #<?php echo Nette\Templating\DefaultHelpers::escapeHtml($var, ENT_NOQUOTES) ?>

<?php }} call_user_func(reset($_l->blocks[$name]), $_l, get_defined_vars()) ;$iterations++; endforeach; array_pop($_l->its); $iterator = end($_l->its) ?>

<?php Nette\Latte\Macros\UIMacros::callBlock($_l, 'dynamic', array('var' => 20) + $template->getParams()) ?>

<?php call_user_func(reset($_l->blocks['static']), $_l, array('var' => 30) + $template->getParams()) ?>

<?php Nette\Latte\Macros\UIMacros::callBlock($_l, $name, array('var' => 40) + $template->getParams()) ?>

<?php //
// block word$name
//
if (!function_exists($_l->blocks["word$name"][] = 'xxx')) { function _lxxx_word_name($_l, $_args) { extract($_args) ;}} call_user_func(reset($_l->blocks["word$name"]), $_l, get_defined_vars()) ?>

<?php //
// block "word$name"
//
if (!function_exists($_l->blocks["word$name"][] = 'xxx')) { function _lxxx__word_name_($_l, $_args) { extract($_args) ;}} call_user_func(reset($_l->blocks["word$name"]), $_l, get_defined_vars()) ?>

<?php
// template extending support
if ($_l->extends) {
	ob_end_clean();
	Nette\Latte\Macros\CoreMacros::includeTemplate($_l->extends, get_defined_vars(), $template)->render();
}