<?php

//

?><?php list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, 'xxx')
;
// snippets support
if (isset($presenter, $control) && $presenter->isAjax() && $control->isControlInvalid()) {
	return Nette\Latte\Macros\UIMacros::renderSnippets($control, $_l, get_defined_vars());
}

//
// main template
//
?>
<p>Included file #1</p>

<?php Nette\Latte\Macros\CoreMacros::includeTemplate("include2.latte", array('localvar' => 20) + $template->getParams(), $_l->templates['xxx'])->render() ?>

<?php Nette\Latte\Macros\CoreMacros::includeTemplate("../include3.latte", $template->getParams(), $_l->templates['xxx'])->render() ?>

<textarea>
pre
</textarea>