<?php

//

?><?php list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, '%[a-z0-9]+%')
;
// snippets support
if (%A%}

//
// main template
//
?>
<p>Included file #1</p>

<?php $_l->templates['%[a-z0-9]+%']->renderChildTemplate("include2.latte", array('localvar' => 20) + $template->getParameters()) ?>

<?php $_l->templates['%[a-z0-9]+%']->renderChildTemplate("../include3.latte", $template->getParameters()) ?>

<textarea>
pre
</textarea>
