<?php
// source: %a%

// prolog Latte\Macros\CoreMacros
list($_l, $_g) = Latte\Macros\CoreMacros::initRuntime($template, '%[a-z0-9]+%')
;
// prolog Latte\Macros\BlockMacros
//
// block title
//
if (!function_exists($_l->blocks['title'][] = '_%[a-z0-9]+%_title')) { function _%[a-z0-9]+%_title($_l, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v
?>My website<?php
}}

//
// block sidebar
//
if (!function_exists($_l->blocks['sidebar'][] = '_%[a-z0-9]+%_sidebar')) { function _%[a-z0-9]+%_sidebar($_l, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v
?>		<ul>
			<li><a href="/">Homepage</a></li>
			<li><a href="/contact">Contact</a></li>
		</ul>
<?php
}}

//
// end of blocks
//

// template extending

$_l->extends = empty($template->_extended) && isset($_control) && $_control instanceof Nette\Application\UI\Presenter ? $_control->findLayoutTemplateFile() : NULL; $template->_extended = $_extended = TRUE;

if ($_l->extends) { ob_start();}

//
// main template
//
extract(array('class' => NULL, 'namespace' => NULL, 'top' => TRUE), EXTR_SKIP) ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<link rel="stylesheet" href="style.css">
	<title><?php if ($_l->extends) { ob_end_clean(); return $template->renderChildTemplate($_l->extends, get_defined_vars()); }
call_user_func(reset($_l->blocks['title']), $_l, get_defined_vars())  ?></title>
</head>

<body>
	<div id="sidebar">
<?php call_user_func(reset($_l->blocks['sidebar']), $_l, get_defined_vars())  ?>
	</div>

	<div id="content">
<?php Latte\Macros\BlockMacros::callBlock($_l, 'content', $template->getParameters()) ?>
	</div>
</body>
</html>
