<?php // source map %a%: {"21":[14],"25":[24],"26":[18],"27":[21],"32":[24],"35":[31],"36":[28],"37":[29],"38":[30],"40":[31],"50":[12]} 


// prolog Nette\Latte\Macros\CoreMacros
list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, '%a%')
;
// prolog Nette\Latte\Macros\UIMacros
//
// block css
//
if (!function_exists($_l->blocks['css'][] = '%a%_css')) { function %a%_css($_l, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v
?>	.no-images img { display: none; }
	.x .y { font-weight: bold; }
<?php
}}

//
// block content
//
if (!function_exists($_l->blocks['content'][] = '%a%_content')) { function %a%_content($_l, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v
;  call_user_func(reset($_l->blocks['title']), $_l, get_defined_vars())      {* original-line 12 *}

;  

 echo Nette\Templating\Helpers::escapeHtml($x, ENT_NOQUOTES)                 {* original-line 14 *}
?>


<ul>
<?php $iterations = 0; foreach ($items as $item) { ?>	<li>
		Item <?php echo Nette\Templating\Helpers::escapeHtml($item->id, ENT_NOQUOTES) ?>:
		<a
		   onmouseover="console.log(this)" href="<?php echo htmlSpecialChars($_control->link("item", array($item->id))) ?>"<?php if ($_l->tmp = array_filter(array($item->superCool ? 'superCool' : NULL))) echo ' class="' . htmlSpecialChars(implode(" ", array_unique($_l->tmp))) . '"' ?>>
			Link
		</a>
	</li>
<?php $iterations++; } 
?>
</ul>

<?php Nette\Latte\Macros\FormMacros::renderFormBegin($form = $_form = $_control["myForm"], array())
?>
	Name: <?php echo $_form["name"]->getControl() ?><br>
	Mail: <?php echo $_form["email"]->getControl() ?><br>
	<?php echo $_form["add"]->getControl()
?>

<?php Nette\Latte\Macros\FormMacros::renderFormEnd($_form)
?>

<hr>
<?php
}}

//
// block title
//
if (!function_exists($_l->blocks['title'][] = '%a%_title')) { function %a%_title($_l, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v
?><h1>Page <?php echo Nette\Templating\Helpers::escapeHtml($name, ENT_NOQUOTES) ?></h1>
<?php
}}

//
// end of blocks
//

// template extending and snippets support

$_l->extends = empty($template->_extended) && isset($_control) && $_control instanceof Nette\Application\UI\Presenter ? $_control->findLayoutTemplateFile() : NULL; $template->_extended = $_extended = TRUE;


if ($_l->extends) {
	ob_start();

} elseif (!empty($_control->snippetMode)) {
	return Nette\Latte\Macros\UIMacros::renderSnippets($_control, $_l, get_defined_vars());
}

//
// main template
//


 

 if ($_l->extends) { ob_end_clean(); return Nette\Latte\Macros\CoreMacros::includeTemplate($_l->extends, get_defined_vars(), $template)->render(); }
call_user_func(reset($_l->blocks['css']), $_l, get_defined_vars()) 

  
?>



<?php call_user_func(reset($_l->blocks['content']), $_l, get_defined_vars()) 

;  

 // end of source map %a%
