<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
	<title>Modules demo</title>
	<link rel="stylesheet" type="text/css" media="screen" href="{$basePath}/css/site.css">
</head>

<body>
	<div id="path">
		<span id="module">{$moduleName}<span id="presenter">{$presenterName}:<span id="view">{$viewName}</span></span></span>
	</div>

	<fieldset>
		<legend>This is layout template <em>{$template->getFile()}</em></legend>

		<h1>Modules demo</h1>

		<fieldset>
			<legend>This is content block template <em>{$presenter->template->getFile()}</em></legend>
			{include #content}
		</fieldset>


		<h2>Absolute links</h2>
		<ul>
			<li><a href="{link :Front:Default:}"><code>:Front:Default:</code></a> - link to presenter <em>Front:Default</em></li>
			<li><a href="{link :Admin:Default:}"><code>:Admin:Default:</code></a> - link to presenter <em>Admin:Default</em></li>
		</ul>
	</fieldset>
</body>
</html>