{block #content}

<h1 n:block="title">My Albums</h1>

<p><a href="{link add}">Add new album</a></p>

<table class="grid">
<tr>
	<th>Title</th>
	<th>Artist</th>
	<th>&nbsp;</th>
</tr>

{foreach $albums as $album}
<tr>
	<td>{$album->title}</td>
	<td>{$album->artist}</td>
	<td>
		<a href="{link edit, $album->id}">Edit</a>
		<a href="{link delete, $album->id}">Delete</a>
	</td>
</tr>
{/foreach}
</table>
