{**
 * Layout of Nette Framework example CD collection (Akrabat)
 *
 * @package    MyApplication
 *
 * @param string   $robots   tell robots how to index the content of a page (optinal)
 * @param string   $basePath web base path
 * @param array    $flashes  flash messages
 * @param Identity $user     logged user (optinal)
 *}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="Content-Language" content="en" />

	<meta name="description" content="Nette Framework example" />
	<meta n:ifset="$robots" name="robots" content="{$robots}">

	<title>{block #title|striptags|trim}{/block} | Nette example</title>

	<link rel="stylesheet" type="text/css" media="screen" href="{$basePath}/css/site.css" />
</head>

<body>
	<div n:foreach="$flashes as $flash" class="flash {$flash->type}">{$flash->message}</div>

	<div id="content">
		{include #content}
	</div>

	<p id="logged-in" n:ifset="$user">Logged in as {$user->real_name}. <a href="{link logout}">Logout</a></p>
</body>
</html>