{**
 * Layout of Nette Framework example CD collection (Akrabat)
 *
 * @copyright  Copyright (c) 2009 John Doe
 * @package    MyApplication
 *
 * @param string   $robots   tell robots how to index the content of a page (optinal)
 * @param string   $basePath web base path
 * @param array    $flashes  flash messages
 * @param Identity $user     logged user (optinal)
 *}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="Content-Language" content="en" />

	<meta name="description" content="Nette Framework example" />
	{if isset($robots)}<meta name="robots" content="{$robots}" />{/if}

	<title>{block #title|upper}{/block} Nette example</title>

	<link rel="stylesheet" type="text/css" media="screen" href="{$basePath}/css/site.css" />
</head>

<body>
	{foreach $flashes as $flash}<div class="flash {$flash->type}">{$flash->message}</div>{/foreach}

	<div id="content">
		{include #content}
	</div>

	{if isset($user)}
	<p id="logged-in">Logged in as {$user->real_name}. <a href="{link logout}">Logout</a></p>
	{/if}
</body>
</html>