for %%f in (test.*.php) do c:\PHP\versions\php-5.1.1-Win32\php.exe -q "%%f" > "output\%%f-5.1.1.html"
for %%f in (test.*.php) do c:\PHP\versions\php-5.1.2-Win32\php.exe -q "%%f" > "output\%%f-5.1.2.html"
for %%f in (test.*.php) do c:\PHP\versions\php-5.1.3-Win32\php.exe -q "%%f" > "output\%%f-5.1.3.html"
for %%f in (test.*.php) do c:\PHP\versions\php-5.1.4-Win32\php.exe -q "%%f" > "output\%%f-5.1.4.html"
for %%f in (test.*.php) do c:\PHP\versions\php-5.1.5-Win32\php.exe -q "%%f" > "output\%%f-5.1.5.html"
for %%f in (test.*.php) do c:\PHP\versions\php-5.1.6-Win32\php.exe -q "%%f" > "output\%%f-5.1.6.html"
for %%f in (test.*.php) do c:\PHP\versions\php-5.2.0-Win32\php.exe -q "%%f" > "output\%%f-5.2.0.html"
for %%f in (test.*.php) do c:\PHP\versions\php-5.2.1-Win32\php.exe -q "%%f" > "output\%%f-5.2.1.html"
for %%f in (test.*.php) do c:\PHP\versions\php-5.2.2-Win32\php.exe -q "%%f" > "output\%%f-5.2.2.html"
for %%f in (test.*.php) do c:\PHP\versions\php-5.2.3-Win32\php.exe -q "%%f" > "output\%%f-5.2.3.html"
for %%f in (test.*.php) do c:\PHP\versions\php-5.2.4-Win32\php.exe -q "%%f" > "output\%%f-5.2.4.html"
for %%f in (test.*.php) do c:\PHP\versions\php-5.2.5-Win32\php.exe -q "%%f" > "output\%%f-5.2.5.html"

@c:\PHP\versions\php-5.1.6-Win32\php.exe -q c:\PHP\versions\hash.php "output\*.html"
