{block #content}
<ul>
	<li><a href="{link addItem}"><code>addItem</code></a> - link to view <em>addItem</em> in current presenter</li>
	<li><a href="{link CatalogList:}"><code>CatalogList:</code></a> - link to presenter <em>CatalogList</em> in current module and view <em>default</em></li>
	<li><a href="{link Export:Default:xml}"><code>Export:Default:xml</code></a> - link to presenter <em>Default</em> in <em>Export</em> submodule and view <em>xml</em></li>
	<li><a href="{link :Admin:Default:}"><code>:Admin:Default:</code></a> - link to presenter <em>Default</em> in <em>Admin</em> module (view <em>default</em>)</li>
</ul>