{**
 * My Application layout template.
 *
 * @copyright  Copyright (c) 2009 John Doe
 * @package    MyApplication
 * @version    $Id$
 *
 * @param string   $title    page title
 * @param string   $robots   tell robots how to index the content of a page (optinal)
 * @param string   $baseUri  web base URI
 * @param array    $flashes  flash messages
 * @param Template $content  view template
 *}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="Content-Language" content="en" />

	<meta name="description" content="Nette Framework web application skeleton" />
	{if isset($robots)}<meta name="robots" content="{$robots}">{/if}

	<title>{$title}</title>

	<link rel="stylesheet" media="screen,projection,tv" href="{$baseUri}css/screen.css" type="text/css" />
	<link rel="stylesheet" media="print" href="{$baseUri}css/print.css" type="text/css" />
	<link rel="shortcut icon" href="{$baseUri}favicon.ico" type="image/x-icon" />
</head>

<body>
	{foreach $flashes as $flash}<div class="flash {$flash->type}">{$flash->message}</div>{/foreach}

	{include #content}
</body>
</html>
