{contentType text}
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
{? $mail->From = "John Doe <doe@example.com>" }
<html>
<head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Hello Jane!</title>
<style>
	p {
		background: yellow url("background.png")
	}
</style>
</head>

<body background="background.png">

	<p>Hello!</p>

	<img src="background.png" width="50">

	<P>One<br>two<p>

	<table>
	<tr>
	<td>three</td>
	<td>four</td>
	</tr>
	<tr>
	<td>five</td>
	<td>six</td>
	</tr>
	</table>

</body>
</html>
