<?php

/**
 * Debug Bar: panel "error" template.
 *
 * This file is part of the Nette Framework.
 * Copyright (c) 2004, 2010 David Grudl (http://davidgrudl.com)
 */

namespace Nette;

use Nette;
?>
<h1>Errors</h1>

<?php $relative = isset($_SERVER['SCRIPT_FILENAME']) ? strtr(dirname(dirname($_SERVER['SCRIPT_FILENAME'])), '/', DIRECTORY_SEPARATOR) : NULL ?>

<div class="nette-inner">
<table>
<?php $i = 0 ?>
<?php foreach (self::$errors as $item => $count): list($message, $file, $line) = explode('|', $item) ?>
<tr class="<?php echo $i++ % 2 ? 'nette-alt' : '' ?>">
	<td class="nette-right"><?php echo $count ? "$count\xC3\x97" : '' ?></td>
	<td><pre><?php echo
		htmlspecialchars($message), ' in ',
		(self::$editor ? '<a href="' . htmlspecialchars(strtr(self::$editor, array('%file' => rawurlencode($file), '%line' => $line))) . '">' : ''),
		htmlspecialchars(($relative ? str_replace($relative, "...", $file) : $file)),
		':', $line,
		(self::$editor ? '</a>' : '')
	?></pre></td>
</tr>
<?php endforeach ?>
</table>
</div>