{block #content}
<ul>
	<li><a href="{link addItem}"><code>addItem</code></a> - link to view <code>addItem</code> in current presenter</li>
	<li><a href="{link CatalogList:}"><code>CatalogList:</code></a> - link to presenter <code>CatalogList</code> in current module and view <code>default</code></li>
	<li><a href="{link Export:Default:xml}"><code>Export:Default:xml</code></a> - link to presenter <code>Default</code> in <code>Export</code> submodule and view <code>xml</code></li>
	<li><a href="{link :Admin:Default:}"><code>:Admin:Default:</code></a> - link to presenter <code>Default</code> in <code>Admin</code> module (view <code>default</code>)</li>
</ul>