
<ul>
	<li>Escaped: {$hello}</li>
	<li>Non-escaped: {!hello}</li>
	<li>Escaped expression: {='<' . 'b' . '>hello' . '</b>'}</li>
	<li>Non-escaped expression: {!='<' . 'b' . '>hello' . '</b>'}</li>
	<li>Array access: {$people[1]}</li>
	<li>Environment variable: {%baseUri%}</li>
</ul>

{* comment *}

{* multi
line
comment *}


<if $hello>
	{$hello}
<elseif $any>
	{$any}
<else>
	none
</if>


<if $hello.test>
	{$hello.test}
	{$hello->test}
</if>



<ul>
<foreach $people as $person>
	<li>{$person}</li>
</foreach>
</ul>


{include 'subdir/include1.phtml'}