<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ul{attr class('item') style('background', 'white') title($hello) compact(TRUE)}>
	<li>Escaped: {$hello}</li>
	<li>Non-escaped: {!$hello}</li>
	<li>Escaped expression: {='<' . 'b' . '>hello' . '</b>'}</li>
	<li>Non-escaped expression: {!='<' . 'b' . '>hello' . '</b>'}</li>
	<li>Array access: {$people[1]}</li>
	<li>Html: {$el}</li>
	<li>Translated: {_$people[1]}</li>
	<li>Non-escaped and translated: {!_$people[1]}</li>
</ul>

<input/> <input /> <input>

<input checked> <input checked="checked">

{ test} {"test} {'test}

<p {attr class('item')}> </p>

<p val = {if true}"a"{else}"b"{/if}> </p>

<p val0 val1 = tmp val2=tmp val3="x"/> </p>

<p val = {$id}> </p>

<p val = />{$id}</p>

{* comment *}

{* multi
line
comment *}


{if $hello}
	{$hello}
{elseif $any}
	{$any}
{else}
	none
{/if}


{foreach array(TRUE) as $foo}
	{foreach $people as $person}
	{if $iterator->isFirst()}<ul id="{$id}">{/if}
	<li id="item-{$iterator->getCounter()}" class="{$iterator->isOdd() ? 'odd' : 'even'}">{$person}</li>
	{if $iterator->isLast()}</ul>{/if}
	{/foreach}
{/foreach}



{include 'subdir/include1.phtml', 'localvar' => 10 |indent}



<style type="text/css">
<!--
#{$id} {
	background: blue;
}
-->
</style>



<script>
<!--
alert('</div>');

var prop = {$people};

document.getElementById({$id}).style.backgroundColor = 'red';

var html = {$el};
-->
</script>


<script>
/* <![CDATA[ */

var prop2 = {$people};

/* ]]> */
</script>


<p onclick =
'alert({$id});alert("hello");'
 title='{$id}"'
 style =
 "color:{$id};'"
 alt='{$el}'
 onfocus="alert({$el})"
>click on me</p>



{include '@menu.phtml'}



{block #menu}
<ul>
	{foreach $menu as $item}
	<li>{if is_array($item)} {include #this, 'menu' => $item} {else}{$item}{/if}</li>
	{/foreach}
</ul>
{/block}


{default varx => 2}{$varx}
{default varx => 4}{$varx}

{assign varx => 7}{$varx}
{var varx => 8}{$varx}
{var $varx => 9}{$varx}

<!-- {$comment} -->


</ul>


<ul>
	<li n:foreach="$people as $person">{$person}</li>
</ul>

<ul>
	<li n:for="$i=0;$i<3;$i++">{$i}</li>
</ul>

<ul>
	<li n:while="--$i>0">{$i}</li>
</ul>

<p n:if="true">
	<div><p>true</div>
</p>

<p n:if="true">
	<div><p>true</p></div>
</p>

<p n:if="false">
	<div><p>true</div>
</p>

<p n:if="false">
	<div><p>true</p></div>
</p>

<p n:if="strlen('{$id}') == 5">noLatte</p>

<ul>
	<li n:if="strlen($person)===4" n:foreach="$people as $person">{$person}</li>
</ul>

<ul n:inner-if="strlen($person)===4" n:inner-foreach="$people as $person">
	<li>{$person|lower}</li>
</ul>

<ul n:block="#bl">
	<li n:if="strlen($person)===4" n:foreach="$people as $person">{$person}</li>
</ul>

<b n:tag-if="true">bold</b> <b n:tag-if="false">normal</b>

<n:include block="#bl" n:modifiers="upper">

<n:default vary=3>{$vary}

<n:assign vary=7>{$vary}

{?

	echo 'test'

}

{l} {r}