<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<title>{$title}</title>
	<link rel="stylesheet" type="text/css" media="screen" href="{$baseUri}css/site.css" />
</head>

<body>
	{if isset($flash)}<div class="flash {$flash->type}">{$flash->message}</div>{/if}

	<div id="content">
	{include $content}
	</div>

	{if isset($user)}
	<p id="logged-in">Logged in as {$user->real_name}. <a href="{$presenter->link('logout')}">Logout</a></p>
	{/if}
</body>
</html>